<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BuildingBlocksProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create parent category "Building Blocks"
        $buildingBlocks = Category::firstOrCreate(
            ['slug' => 'building-blocks'],
            [
                'name' => 'Building Blocks',
                'name_ar' => 'مكعبات البناء',
                'description' => 'Construction and building block sets for creative play',
                'description_ar' => 'مجموعات البناء والتركيب للعب الإبداعي',
                'image' => 'categories/building-blocks.webp',
                'sort_order' => 3,
                'is_active' => true,
            ]
        );

        // Get or create sub-category "Building Models"
        $buildingModels = Category::firstOrCreate(
            ['slug' => 'building-models'],
            [
                'name' => 'Building Models',
                'name_ar' => 'نماذج البناء',
                'description' => 'Detailed building model sets',
                'description_ar' => 'مجموعات نماذج البناء المفصلة',
                'parent_id' => $buildingBlocks->id,
                'sort_order' => 1,
                'is_active' => true,
            ]
        );

        // Hardcoded products array - all 58 Sluban building blocks products
        $products = [
            [
                'sku' => 'M38-B1268',
                'name_en' => 'Metropolis-D.C. Department Store 718pcs',
                'name_ar' => 'متجر متروبوليس متعدد الأقسام – طقم تركيب 725 قطعة',
                'description_en' => 'The Metropolis Department Store Building Set is a beautifully detailed construction kit from the Metropolis series. Kids can build a complete shopping store and even combine it with other sets like the Crowne Hotel to create a full city scene. Made from high-quality, durable ABS plastic, this set inspires creativity and imaginative play.',
                'description_ar' => 'طقم تركيب متجر متروبوليس متعدد الأقسام هو مجموعة بناء رائعة من سلسلة Metropolis، تتيح للأطفال إنشاء متجر تسوق متكامل بتصميم أنيق وتفاصيل واقعية.',
                'price' => 38.78,
                'stock' => 48,
                'thumbnail' => 'M38-B1268.webp',
                'images' => 'M38-B1268-4.webp, M38-B1268-2.webp, M38-B1268-1.webp',
            ],
            [
                'sku' => 'M38-B1289',
                'name_en' => 'Metropolis-Delivery Truck 269pcs',
                'name_ar' => 'شاحنة التوصيل متروبوليس – طقم تركيب 269 قطعة',
                'description_en' => 'The Metropolis Delivery Truck Building Set lets kids build a realistic delivery truck to add action and detail to their Metropolis city.',
                'description_ar' => 'طقم تركيب شاحنة التوصيل من سلسلة متروبوليس يمنح الأطفال تجربة بناء ممتعة ومليئة بالتفاصيل.',
                'price' => 18.09,
                'stock' => 48,
                'thumbnail' => 'M38-B1289.webp',
                'images' => 'M38-B1289-1.webp',
            ],
            [
                'sku' => 'M38-B1288',
                'name_en' => 'Metropolis-Rescue Vehicle(Pull back) 272pcs',
                'name_ar' => 'مركبة الإنقاذ متروبوليس بسحب خلفي – طقم تركيب 272 قطعة',
                'description_en' => 'The Metropolis Rescue Vehicle Pull-Back Building Set offers kids a fun and interactive building experience with a pull-back motor feature.',
                'description_ar' => 'طقم تركيب مركبة الإنقاذ من سلسلة متروبوليس يمنح الأطفال تجربة بناء ممتعة مع حركة إضافية بفضل خاصية السحب الخلفي.',
                'price' => 18.09,
                'stock' => 48,
                'thumbnail' => 'M38-B1288.webp',
                'images' => 'M38-B1288-4.webp, M38-B1288-3.webp, M38-B1288-2.webp, M38-B1288-1.webp',
            ],
            [
                'sku' => 'M38-B1286',
                'name_en' => 'Metropolis-Ferris Wheel 504pcs',
                'name_ar' => 'عجلة فيريس متروبوليس – طقم تركيب 504 قطعة',
                'description_en' => 'Experience the funfair buzz with the Metropolis Ferris Wheel, a 504-piece set that brings life and creativity to any cityscape.',
                'description_ar' => 'استمتع بأجواء الملاهي مع طقم تركيب عجلة فيريس من سلسلة متروبوليس، الذي يضم 504 قطعة.',
                'price' => 21.54,
                'stock' => 48,
                'thumbnail' => 'M38-B1286.webp',
                'images' => 'M38-B1286-4.webp, M38-B1286-3.webp, M38-B1286-2.webp, M38-B1286-1.webp',
            ],
            [
                'sku' => 'M38-B1285',
                'name_en' => 'Metropolis-Roller Coaster 448pcs',
                'name_ar' => 'قطار الملاهي متروبوليس – طقم تركيب 448 قطعة',
                'description_en' => 'Step into the world of fun with the Metropolis Roller Coaster Building Set, a 448-piece amusement park kit.',
                'description_ar' => 'استمتع بأجواء مدينة الملاهي مع طقم تركيب قطار الملاهي من سلسلة متروبوليس.',
                'price' => 21.54,
                'stock' => 48,
                'thumbnail' => 'M38-B1285.webp',
                'images' => 'M38-B1285-5.webp, M38-B1285-3.webp, M38-B1285-2.webp, M38-B1285-1.webp',
            ],
            [
                'sku' => 'M38-B1283',
                'name_en' => 'Metropolis-Star Gate 288pcs',
                'name_ar' => 'بوابة النجوم متروبوليس – طقم تركيب 288 قطعة',
                'description_en' => 'Step into a world of fantasy with the Metropolis Star Gate Building Set, a 288-piece magical set.',
                'description_ar' => 'اكتشف عالم الخيال مع طقم تركيب بوابة النجوم من سلسلة متروبوليس.',
                'price' => 16.37,
                'stock' => 48,
                'thumbnail' => 'M38-B1283.webp',
                'images' => 'M38-B1283-3.webp, M38-B1283-5.webp, M38-B1283-2.webp, M38-B1283-1.webp',
            ],
            [
                'sku' => 'M38-B1273',
                'name_en' => 'ModelBricks-1/44 J16 AIRCRAFT CARRIER (RU SU-30) 1041pcs',
                'name_ar' => 'حاملة طائرات نموذجية J16 SU-30 – طقم تركيب 1041 قطعة',
                'description_en' => 'Discover the ModelBricks J16 SU-30 Aircraft Carrier building set, featuring 1041 pieces for a highly detailed military jet model.',
                'description_ar' => 'اكتشف نموذج حاملة الطائرات J16 SU-30 من ModelBricks، طقم تركيب مكون من 1041 قطعة.',
                'price' => 51.72,
                'stock' => 24,
                'thumbnail' => 'M38-B1273.webp',
                'images' => 'M38-B1273-6.webp, M38-B1273-5.webp, M38-B1273-4.webp, M38-B1273-3.webp, M38-B1273-1.webp',
            ],
            [
                'sku' => 'M38-B1267',
                'name_en' => 'Metropolis-D.C. Crowne Hotel 428pcs',
                'name_ar' => 'فندق كراون متروبوليس – طقم تركيب 428 قطعة',
                'description_en' => 'Give kids an engaging building experience with the Metropolis D.C. Crowne Hotel set, featuring 428 pieces.',
                'description_ar' => 'امنح الأطفال تجربة بناء ممتعة ومفصلة مع طقم تركيب فندق كراون من سلسلة متروبوليس.',
                'price' => 21.54,
                'stock' => 48,
                'thumbnail' => 'M38-B1267.webp',
                'images' => 'M38-B1267-5.webp, M38-B1267-3.webp, M38-B1267-2.webp, M38-B1267-1.webp',
            ],
            [
                'sku' => 'M38-B1266',
                'name_en' => 'Metropolis-Slubucks 241pcs',
                'name_ar' => 'مقهى سلوبوكس متروبوليس – طقم تركيب 241 قطعة',
                'description_en' => 'Bring fun and creativity to your Metropolis city with the Slubucks Café Building Set, featuring 241 pieces.',
                'description_ar' => 'أضف لمسة من الحياة والمرح إلى مدينة متروبوليس مع طقم تركيب مقهى سلوبوكس.',
                'price' => 13.78,
                'stock' => 48,
                'thumbnail' => 'M38-B1266.webp',
                'images' => 'M38-B1266-5.webp, M38-B1266-3.webp, M38-B1266-2.webp, M38-B1266-1.webp',
            ],
            [
                'sku' => 'M38-B1263',
                'name_en' => 'Metropolis-Central Train Station 592pcs',
                'name_ar' => 'محطة القطار المركزية متروبوليس – طقم تركيب 592 قطعة',
                'description_en' => 'Enjoy a detailed building experience with the Metropolis Central Train Station set, featuring 592 pieces and 7 innovative mini-figures.',
                'description_ar' => 'استمتع بتجربة بناء مفصلة مع طقم محطة القطار المركزية من سلسلة متروبوليس.',
                'price' => 38.78,
                'stock' => 48,
                'thumbnail' => 'M38-B1263.webp',
                'images' => 'M38-B1263-6.webp, M38-B1263-4.webp, M38-B1263-3.webp, M38-B1263-1.webp',
            ],
            [
                'sku' => 'M38-B1262',
                'name_en' => 'Metropolis-New Energy Vehicle 4S Store 371pcs',
                'name_ar' => 'متجر الطاقة متروبوليس – طقم تركيب 371 قطعة',
                'description_en' => 'Give kids a fun building experience with the Metropolis Energy Vehicle 4S Store set, featuring 371 pieces.',
                'description_ar' => 'امنح الأطفال تجربة بناء ممتعة مع طقم متجر الطاقة من سلسلة متروبوليس.',
                'price' => 21.54,
                'stock' => 48,
                'thumbnail' => 'M38-B1262.webp',
                'images' => 'M38-B1262-5.webp, M38-B1262-4.webp, M38-B1262-2.webp',
            ],
            [
                'sku' => 'M38-B1261',
                'name_en' => 'Metropolis-New Energy Bus 239pcs',
                'name_ar' => 'حافلة الطاقة الجديدة متروبوليس – طقم تركيب 239 قطعة',
                'description_en' => 'Enjoy educational building fun with the Metropolis New Energy Bus set, featuring 239 pieces.',
                'description_ar' => 'استمتع بالبناء واللعب التعليمي مع طقم حافلة الطاقة الجديدة من سلسلة متروبوليس.',
                'price' => 13.78,
                'stock' => 48,
                'thumbnail' => 'M38-B1261.webp',
                'images' => 'M38-B1261-7.webp, M38-B1261-5.webp, M38-B1261-4.webp, M38-B1261-1.webp',
            ],
            [
                'sku' => 'M38-B1258',
                'name_en' => 'ARMY-OEF-Stryker ADS 310pcs',
                'name_ar' => 'وحدة سترايكر ADS – طقم تركيب 310 قطعة',
                'description_en' => 'Discover tactical building fun with the Sluban OEF Stryker ADS set, featuring 310 pieces.',
                'description_ar' => 'اكتشف متعة البناء والتكتيك مع طقم وحدة سترايكر ADS من Sluban.',
                'price' => 17.23,
                'stock' => 48,
                'thumbnail' => 'M38-B1258.webp',
                'images' => 'M38-B1258-5.webp, M38-B1258-4.webp, M38-B1258-2.webp, M38-B1258-1.webp',
            ],
            [
                'sku' => 'M38-B1256',
                'name_en' => 'ARMY-OEF-M1XS Main Battle Tank 314pcs',
                'name_ar' => 'دبابة قتال رئيسية – 314 قطعة',
                'description_en' => 'Get ready for an exciting and tactical experience with the ARMY-OEF-M1XS Main Battle Tank!',
                'description_ar' => 'استعد لتجربة مليئة بالإثارة والتكتيك مع دبابة القتال الرئيسية ARMY-OEF-M1XS!',
                'price' => 17.23,
                'stock' => 48,
                'thumbnail' => 'M38-B1256.webp',
                'images' => 'M38-B1256-1.webp, M38-B1256-2.webp, M38-B1256-3.webp, M38-B1256-4.webp',
            ],
            [
                'sku' => 'M38-P8015',
                'name_en' => 'PLEYERID-Music Box-LOVE CONFESSION',
                'name_ar' => 'بلاير آيد – صندوق الموسيقى – اعتراف الحب',
                'description_en' => 'Enjoy building and creating your own world with the Sluban M38-P8015! High-quality pieces that develop assembly skills.',
                'description_ar' => 'استمتع ببناء وتشكيل عالمك الخاص مع Sluban M38-P8015!',
                'price' => 31.03,
                'stock' => 36,
                'thumbnail' => 'M38-P8015-1.webp',
                'images' => 'M38-P8015-2.webp',
            ],
            [
                'sku' => 'M38-P8161',
                'name_en' => 'PLEYERID-Peacock(with Lighting)',
                'name_ar' => 'PLEYERID – طائر الطاووس (مع إضاءة)',
                'description_en' => 'Add a touch of charm and beauty to your room with the PLEYERID Peacock with Lighting!',
                'description_ar' => 'أضف لمسة من السحر والجمال إلى غرفتك مع PLEYERID – طائر الطاووس المزود بإضاءة!',
                'price' => 33.61,
                'stock' => 36,
                'thumbnail' => 'M38-P8161.webp',
                'images' => 'M38-P8161-2.webp, M38-P8161-3.webp, M38-P8161-1.webp',
            ],
            [
                'sku' => 'M38-P8160',
                'name_en' => 'PLEYERID-Swans(with Lighting) 932pcs',
                'name_ar' => 'PLEYERID - البجع مع إضاءة (932 قطعة)',
                'description_en' => 'Enjoy building this stunning PLEYERID set consisting of 932 pieces with a lighting system.',
                'description_ar' => 'استمتع ببناء هذا المجسم الرائع من PLEYERID المكوَّن من 932 قطعة.',
                'price' => 33.61,
                'stock' => 36,
                'thumbnail' => 'M38-P8160.webp',
                'images' => 'M38-P8160-1.webp',
            ],
            [
                'sku' => 'M38-P8070',
                'name_en' => 'PLEYERID-roses 313pcs',
                'name_ar' => 'PLEYERID - ورود (313 قطعة)',
                'description_en' => 'Enjoy building this exquisite PLEYERID set consisting of 313 pieces.',
                'description_ar' => 'استمتع ببناء هذا المجسم الجميل من PLEYERID المكوَّن من 313 قطعة.',
                'price' => 14.65,
                'stock' => 72,
                'thumbnail' => 'M38-P8070.webp',
                'images' => 'M38-P8070-1.webp',
            ],
            [
                'sku' => 'M38-P8061',
                'name_en' => 'PLEYERID-Red roses(Plated vases) 313pcs',
                'name_ar' => 'PLEYERID - الورود الحمراء (مزهرية مطلية) 313 قطعة',
                'description_en' => 'Enjoy building this stunning PLEYERID set with elegant plated vase.',
                'description_ar' => 'PLEYERID - الورود الحمراء (مزهرية مطلية) 313 قطعة',
                'price' => 14.65,
                'stock' => 72,
                'thumbnail' => 'M38-P8061.webp',
                'images' => 'M38-P8061-1.webp',
            ],
            [
                'sku' => 'M38-P8027',
                'name_en' => 'PLEYERID-Hand-cranked merry-go-round 3 types',
                'name_ar' => 'PLEYERID - لعبة الدوّامة اليدوية (3 تصاميم مختلفة)',
                'description_en' => 'Enjoy a delightful building experience with the PLEYERID Hand-Cranked Merry-Go-Round.',
                'description_ar' => 'استمتع بتجربة بناء ممتعة مع لعبة الدوّامة اليدوية من PLEYERID.',
                'price' => 7.75,
                'stock' => 27,
                'thumbnail' => 'M38-P8027.webp',
                'images' => 'M38-P8027-1.webp, M38-P8027-2.webp',
            ],
            [
                'sku' => 'M38-P8018',
                'name_en' => 'PLEYERID-X-MIU-CAT 01',
                'name_ar' => 'بلايريد × ميو كات 01',
                'description_en' => 'PLEYERID X MIU CAT 01 is a special edition piece that combines modern design with a bold, distinctive character.',
                'description_ar' => 'قطعة PLEYERID × MIU CAT 01 تمثّل إصدارًا خاصًا يجمع بين التصميم العصري والطابع الجريء.',
                'price' => 34.47,
                'stock' => 18,
                'thumbnail' => 'M38-P8018.webp',
                'images' => 'M38-P8018-1.webp',
            ],
            [
                'sku' => 'M38-B1291',
                'name_en' => 'ModelBricks-1/350 USS MISSOURI S 1739pcs',
                'name_ar' => 'موديل بريكس – نموذج تركيب لسفينة يو إس إس ميزوري – 1739 قطعة',
                'description_en' => 'The ModelBricks USS Missouri is a detailed building model of the legendary USS Missouri battleship.',
                'description_ar' => 'قطعة ModelBricks USS Missouri هي نموذج تركيب تفصيلي لسفينة البارجة الأمريكية الشهيرة.',
                'price' => 64.65,
                'stock' => 12,
                'thumbnail' => 'M38-B1291.webp',
                'images' => 'M38-B1291-1.webp',
            ],
            [
                'sku' => 'M38-P8013',
                'name_en' => 'PLEYERID-Music Box-SONATA OF LOVE',
                'name_ar' => 'بلايريد – صندوق موسيقي – سوناتا الحب',
                'description_en' => 'A harmonious expression of emotion and elegance inspired by the timeless beauty of music.',
                'description_ar' => 'هو تجسيد متناغم للمشاعر والرقي. مستوحى من جمال الموسيقى الخالد.',
                'price' => 31.03,
                'stock' => 36,
                'thumbnail' => 'M38-P8013.webp',
                'images' => 'M38-P8013-1.webp',
            ],
            [
                'sku' => 'M38-B1335',
                'name_en' => 'POWER BRICKS-Formula car(Pull back) 210pcs',
                'name_ar' => 'باور بريكس – سيارة فورمولا (نظام السحب للخلف) – 210 قطعة',
                'description_en' => 'An exciting building set designed for speed lovers with a pull-back motor.',
                'description_ar' => 'هي مجموعة تركيب ممتعة تجمع بين الإبداع وروح السباق.',
                'price' => 12.06,
                'stock' => 72,
                'thumbnail' => 'M38-B1335.webp',
                'images' => 'M38-B1335-1.webp',
            ],
            [
                'sku' => 'M38-B1332',
                'name_en' => 'POWER BRICKS-Vintage car(Pull back) 238pcs',
                'name_ar' => 'باور بريكس – سيارة كلاسيكية (نظام السحب للخلف) – 238 قطعة',
                'description_en' => 'Brings classic automotive charm to life through an engaging building experience.',
                'description_ar' => 'تجسّد روح السيارات الكلاسيكية من خلال تجربة تركيب ممتعة.',
                'price' => 12.06,
                'stock' => 72,
                'thumbnail' => 'M38-B1332.webp',
                'images' => '',
            ],
            [
                'sku' => 'M38-B1292',
                'name_en' => 'ModelBricks-1/35 FOKKER DR-1S 281pcs',
                'name_ar' => 'طائرة فوكر DR-1S الحرب العالمية الأولى – طقم تركيب 281 قطعة',
                'description_en' => 'Experience precise and historical building with the MB WW1 Fokker DR-1S model kit.',
                'description_ar' => 'استمتع بتجربة بناء دقيقة وتاريخية مع طقم طائرة فوكر DR-1S.',
                'price' => 13.78,
                'stock' => 72,
                'thumbnail' => 'M38-B1292.webp',
                'images' => 'M38-B1292-6.webp, M38-B1292-5.webp, M38-B1292-4.webp, M38-B1292-3.webp, M38-B1292-1.webp',
            ],
            [
                'sku' => 'M38-B1101-11',
                'name_en' => 'PLEYERID-Blue Rose 238PCS',
                'name_ar' => 'زهرة زرقاء – طقم تركيب 238 قطعة',
                'description_en' => 'Give kids a fun and creative building experience with the Sluban Blue Rose set.',
                'description_ar' => 'امنح الأطفال تجربة بناء ممتعة مع طقم زهرة زرقاء من Sluban.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-11.webp',
                'images' => 'M38-B1101-11-4.webp, M38-B1101-11-2.webp, M38-B1101-11-1.webp',
            ],
            [
                'sku' => 'M38-B1119',
                'name_en' => 'ModelBricks- Fishing-boat 610pcs',
                'name_ar' => 'قارب صيد – طقم تركيب 610 قطعة',
                'description_en' => 'Enjoy an innovative building experience with the Sluban Fishing Boat set.',
                'description_ar' => 'استمتع بتجربة بناء مبتكرة مع طقم قارب الصيد من Sluban.',
                'price' => 24.99,
                'stock' => 36,
                'thumbnail' => 'M38-B1119.webp',
                'images' => 'M38-B1119-5.webp, M38-B1119-3.webp, M38-B1119-1.webp',
            ],
            [
                'sku' => 'M38-B1118',
                'name_en' => 'ModelBricks- The Great Shark 592pcs',
                'name_ar' => 'سفينة القرش العظيمة – طقم تركيب 592 قطعة',
                'description_en' => 'Enjoy building the Sluban Great Shark Ship, featuring 592 pieces from the City series.',
                'description_ar' => 'استمتع ببناء سفينة القرش العظيمة من Sluban.',
                'price' => 24.99,
                'stock' => 36,
                'thumbnail' => 'M38-B1118.webp',
                'images' => 'M38-B1118-1.webp, M38-B1118-4.webp, M38-B1118-3.webp',
            ],
            [
                'sku' => 'M38-B1112A',
                'name_en' => 'PLEYERID-Mechanical Bulldog',
                'name_ar' => 'روبوت بولدوج – طقم تركيب 890 قطعة',
                'description_en' => 'Enjoy an interactive building experience with the Sluban Bulldog Robot, featuring 890 pieces.',
                'description_ar' => 'استمتع بتجربة بناء تفاعلية مع روبوت بولدوج من Sluban.',
                'price' => 33.61,
                'stock' => 18,
                'thumbnail' => 'M38-B1112A.webp',
                'images' => 'M38-B1112A-6.webp, M38-B1112A-4.webp, M38-B1112A-2.webp',
            ],
            [
                'sku' => 'M38-B1101-17',
                'name_en' => 'PLEYERID-Peony 198PCS',
                'name_ar' => 'زهرة الفاوانيا – طقم تركيب 198 قطعة',
                'description_en' => 'Discover the beauty of building the Sluban Peony, featuring 198 pieces.',
                'description_ar' => 'اكتشف جمال بناء زهرة الفاوانيا من Sluban.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-17.webp',
                'images' => 'M38-B1101-17-5.webp, M38-B1101-17-3.webp, M38-B1101-17-1.webp',
            ],
            [
                'sku' => 'M38-B1101-16',
                'name_en' => 'PLEYERID-Daisy 255PCS',
                'name_ar' => 'طقم بناء قفل متعدد الألوان – 221 قطعة',
                'description_en' => 'Enjoy building the Sluban Multicolor Clamp set, featuring 221 pieces.',
                'description_ar' => 'استمتع ببناء مجموعة القفل متعدد الألوان من Sluban.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-16.webp',
                'images' => 'M38-B1101-16-4.webp, M38-B1101-16-3.webp, M38-B1101-16-1.webp',
            ],
            [
                'sku' => 'M38-B1101-14',
                'name_en' => 'PLEYERID-Lavender 258PCS',
                'name_ar' => 'ترتيب زهور الخزامى الصناعية مع إناء – ارتفاع 42.6 سم',
                'description_en' => 'Bring a touch of Provence to your home with the Sluban Artificial Lavender Arrangement.',
                'description_ar' => 'أضف لمسة من جمال بروفانس إلى منزلك مع ترتيب زهور الخزامى الصناعية.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-14.webp',
                'images' => 'M38-B1101-14-5.webp, M38-B1101-14-3.webp, M38-B1101-14-1.webp',
            ],
            [
                'sku' => 'M38-B1101-13',
                'name_en' => 'PLEYERID-Freesia 241PCS',
                'name_ar' => 'طقم بناء زهور فريزيا – 241 قطعة',
                'description_en' => 'Add a touch of creativity to your child\'s room with the Sluban Pleyerid Freesia Flower set.',
                'description_ar' => 'أضف لمسة من الإبداع إلى غرفة طفلك مع طقم بناء زهور فريزيا.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-13.webp',
                'images' => 'M38-B1101-13-6.webp, M38-B1101-13-4.webp, M38-B1101-13-1.webp, M38-B1101-13-5.webp, M38-B1101-13-3.webp',
            ],
            [
                'sku' => 'M38-B1122',
                'name_en' => 'ModelBricks- TITANIC 1/350(2370PCS)',
                'name_ar' => 'طقم بناء سفينة كبيرة – 2401 قطعة مع شخصيتين صغيرتين',
                'description_en' => 'Experience the grandeur of classic ships with the 2401-piece Big Shape Ship building set.',
                'description_ar' => 'استمتع بتجربة بناء السفن الكلاسيكية مع طقم البناء الكبير المكوّن من 2401 قطعة.',
                'price' => 107.75,
                'stock' => 9,
                'thumbnail' => 'M38-B1122.webp',
                'images' => 'M38-B1122-6.webp, M38-B1122-4.webp, M38-B1122-3.webp, M38-B1122-2.webp, M38-B1122-1.webp',
            ],
            [
                'sku' => 'M38-B1101-09',
                'name_en' => 'PLEYERID-lilies of the valley 253PCS',
                'name_ar' => 'طقم بناء أزهار زنبق الوادي مع فازة بيضاء – 42 سم',
                'description_en' => 'Bring a creative touch of nature into your home with the Lily of the Valley Building Block set.',
                'description_ar' => 'أضف لمسة طبيعية وعملية إلى منزلك مع طقم بناء أزهار زنبق الوادي المبتكر.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-09.webp',
                'images' => 'M38-B1101-09-2.webp, M38-B1101-09-1.webp',
            ],
            [
                'sku' => 'M38-B1101-08',
                'name_en' => 'PLEYERID-Tibouchina urvilleana 251PCS',
                'name_ar' => 'طقم بناء أزهار تيبوشينا أورفيليانا – 251 قطعة',
                'description_en' => 'Unleash creativity with the Tibouchina Urvilleana building set from the Sluban Pleyerid Flowers range.',
                'description_ar' => 'أطلق العنان لإبداع الأطفال مع طقم أزهار تيبوشينا أورفيليانا.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-08.webp',
                'images' => 'M38-B1101-08-4.webp, M38-B1101-08-2.webp, M38-B1101-08-1.webp',
            ],
            [
                'sku' => 'M38-B1101-06',
                'name_en' => 'PLEYERID-Lotus 258PCS',
                'name_ar' => 'طقم بناء أزهار لوتس – 258 قطعة',
                'description_en' => 'Enjoy fun and educational building with the Lotus set from Sluban Pleyerid Flowers.',
                'description_ar' => 'امنح الأطفال تجربة بناء ممتعة وتعليمية مع طقم أزهار اللوتس.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-06.webp',
                'images' => 'M38-B1101-06-5.webp, M38-B1101-06-2.webp, M38-B1101-06-1.webp',
            ],
            [
                'sku' => 'M38-B1101-04',
                'name_en' => 'PLEYERID-Red Rose 258PCS',
                'name_ar' => 'طقم بناء أزهار الوردة الحمراء – 254 قطعة',
                'description_en' => 'Enjoy fun and educational building with the Red Rose set from Sluban Pleyerid Flowers.',
                'description_ar' => 'امنح الأطفال تجربة بناء ممتعة وتعليمية مع طقم الوردة الحمراء.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-04.webp',
                'images' => 'M38-B1101-04-4.webp, M38-B1101-04-2.webp, M38-B1101-04-1,jpg.webp',
            ],
            [
                'sku' => 'M38-B1101-03',
                'name_en' => 'PLEYERID-Protea Cynaroides 219PCS',
                'name_ar' => 'بلايريد – زهرة بروتيا سيناروييد – 219 قطعة',
                'description_en' => 'A detailed building model inspired by the stunning Protea Cynaroides.',
                'description_ar' => 'هو نموذج تركيب مستوحى من زهرة البروتيا سيناروييد الرائعة.',
                'price' => 10.34,
                'stock' => 96,
                'thumbnail' => 'M38-B1101-03.webp',
                'images' => 'M38-B1101-03-22.webp, M38-B1101-03-11.webp, M38-B1101-03-4.webp, M38-B1101-03-2.webp, M38-B1101-03-1.webp',
            ],
            [
                'sku' => 'M38-B0956',
                'name_en' => 'ModelBricks- Racing Car 283PCS',
                'name_ar' => 'موديل بريكس – سيارة سباق – 283 قطعة',
                'description_en' => 'An engaging construction model designed for fans of high-speed racing.',
                'description_ar' => 'هو نموذج تركيب ممتع لعشاق سيارات السباق عالية السرعة.',
                'price' => 12.06,
                'stock' => 72,
                'thumbnail' => 'M38-B0956.webp',
                'images' => 'M38-B0956-1.webp, M38-B0956-2.webp',
            ],
            [
                'sku' => 'M38-B0955',
                'name_en' => 'ModelBricks- Racing Car 262PCS',
                'name_ar' => 'موديل بريكس – سيارة سباق – 262 قطعة',
                'description_en' => 'A dynamic building model inspired by high-performance racing cars.',
                'description_ar' => 'هو نموذج تركيب مستوحى من سيارات السباق عالية الأداء.',
                'price' => 12.06,
                'stock' => 72,
                'thumbnail' => 'M38-B0955.webp',
                'images' => 'M38-B0955-1.webp',
            ],
            [
                'sku' => 'M38-B0836',
                'name_en' => 'sluban ModelBricks USS Constitution 1X-21 Frigate 1:170',
                'name_ar' => 'سلوبان موديل بريكس سفينة يو إس إس كونستيتيوشن 1X-21 فرقاطة – بمقياس 1:170',
                'description_en' => 'A detailed building set from sluban ModelBricks that recreates the legendary USS Constitution warship.',
                'description_ar' => 'مجموعة تركيب مميزة من sluban ModelBricks تجسّد السفينة الحربية التاريخية USS Constitution.',
                'price' => 42.23,
                'stock' => 24,
                'thumbnail' => 'M38-B0836.webp',
                'images' => 'M38-B0836-4.webp, M38-B0836-3.webp, M38-B0836-2.webp, M38-B0836-1.webp',
            ],
            [
                'sku' => 'M38-B1254',
                'name_en' => 'sluban Army Joint Assault – 744 Pieces Building Set',
                'name_ar' => 'سلوبان مجموعة هجوم مشترك (744 قطعة)',
                'description_en' => 'An action-packed military building set from sluban Army featuring 744 pieces.',
                'description_ar' => 'مجموعة تركيب عسكرية مميزة من sluban Army تضم 744 قطعة.',
                'price' => 34.47,
                'stock' => 32,
                'thumbnail' => 'M38-B1254.webp',
                'images' => 'M38-B1254-4.webp, M38-B1254-3.webp, M38-B1254-2.webp, M38-B1254-1.webp',
            ],
            [
                'sku' => 'M38-B1219',
                'name_en' => 'sluban Metropolis Police – Invasion Command Vehicle (Pull Back)',
                'name_ar' => 'سلوبان مركبة القيادة لمواجهة الغزو (خاصية السحب للخلف)',
                'description_en' => 'A dynamic command vehicle from sluban Metropolis Police, featuring a modern design and pull-back action.',
                'description_ar' => 'مركبة قيادة مميزة من sluban Metropolis Police بتصميم عصري وميزة السحب للخلف.',
                'price' => 21.54,
                'stock' => 36,
                'thumbnail' => 'M38-B1219.webp',
                'images' => 'M38-B1219-3.webp, M38-B1219-2.webp, M38-B1219-1.webp',
            ],
            [
                'sku' => 'M38-B1253',
                'name_en' => 'sluban Army T14S Armata Tank – 319 Pieces Building Set',
                'name_ar' => 'سلوبان آرمـي دبابة أرماتا تي-14 إس – 319 قطعة',
                'description_en' => 'A military building set from sluban Army that lets you build the powerful T14S Armata Tank.',
                'description_ar' => 'مجموعة تركيب عسكرية من sluban Army تتيح بناء دبابة T14S Armata.',
                'price' => 16.37,
                'stock' => 48,
                'thumbnail' => 'M38-B1253-1.webp',
                'images' => 'M38-B1253-5.webp, M38-B1253-4.webp, M38-B1253-3.webp, M38-B1253-2.webp',
            ],
            [
                'sku' => 'M38-B1252',
                'name_en' => 'sluban ModelBricks Pantsir-S1S Self-Propelled ADS – 659 Pieces',
                'name_ar' => 'سلوبان موديل بريكس منظومة بانتسير إس-1 إس ذاتية الحركة – 659 قطعة',
                'description_en' => 'A detailed building set from sluban ModelBricks that allows you to build the Pantsir-S1S self-propelled air defense system.',
                'description_ar' => 'مجموعة تركيب متقدمة من سلوبان موديل بريكس تتيح بناء منظومة بانتسير إس-1 إس.',
                'price' => 24.99,
                'stock' => 36,
                'thumbnail' => 'M38-B1252.webp',
                'images' => 'M38-B1252-4.webp, M38-B1252-3.webp, M38-B1252-2.webp, M38-B1252-1.webp',
            ],
            [
                'sku' => 'M38-B1251',
                'name_en' => 'sluban ModelBricks BTR80AS Infantry Fighting Vehicle 2 in 1 – 611 Pieces',
                'name_ar' => 'سلوبان موديل بريكس مدرعة المشاة بي تي آر 80 إيه إس (2 في 1) – 611 قطعة',
                'description_en' => 'A versatile building set from sluban ModelBricks that lets you build the BTR80AS infantry fighting vehicle with a 2-in-1 build option.',
                'description_ar' => 'مجموعة تركيب مميزة من سلوبان موديل بريكس تتيح بناء مدرعة المشاة بي تي آر 80 إيه إس.',
                'price' => 24.13,
                'stock' => 48,
                'thumbnail' => 'M38-B1251.webp',
                'images' => 'M38-B1251-4.webp, M38-B1251-3.webp, M38-B1251-2.webp, M38-B1251-1.webp',
            ],
            [
                'sku' => 'M38-B1250',
                'name_en' => 'sluban ModelBricks BMD-2S Airborne Armored Vehicle 2 in 1 – 516 Pieces',
                'name_ar' => 'سلوبان موديل بريكس مدرعة الإنزال الجوي بي إم دي-2 إس (2 في 1) – 516 قطعة',
                'description_en' => 'A detailed building set from sluban ModelBricks that allows you to build the BMD-2S airborne armored vehicle.',
                'description_ar' => 'مجموعة تركيب مميزة من سلوبان موديل بريكس تتيح بناء مدرعة الإنزال الجوي بي إم دي-2 إس.',
                'price' => 18.09,
                'stock' => 48,
                'thumbnail' => 'M38-B1250.webp',
                'images' => 'M38-B1250-4.webp, M38-B1250-3.webp, M38-B1250-2.webp, M38-B1250-1.webp',
            ],
            [
                'sku' => 'M38-B1234',
                'name_en' => 'sluban ModelBricks 1/35 ZTZ-99AS Tank (Metal Coating Version) – 1079 Pieces',
                'name_ar' => 'سلوبان موديل بريكس دبابة زد تي زد-99 إيه إس (نسخة بطبقة معدنية) – 1079 قطعة',
                'description_en' => 'A premium building set from sluban ModelBricks to construct the ZTZ-99AS tank with a metal coating.',
                'description_ar' => 'مجموعة تركيب فاخرة من سلوبان موديل بريكس لبناء دبابة زد تي زد-99 إيه إس.',
                'price' => 51.72,
                'stock' => 18,
                'thumbnail' => 'M38-B1234.webp',
                'images' => 'M38-B1234-4.webp, M38-B1234-3.webp, M38-B1234-2.webp, M38-B1234-1.webp',
            ],
            [
                'sku' => 'M38-B1233',
                'name_en' => 'sluban ModelBricks 1/35 WZ-10S (Metal Coating Version) – 914 Pieces',
                'name_ar' => 'سلوبان موديل بريكس هليكوبتر دبابة WZ-10S (نسخة بطبقة معدنية) – 914 قطعة',
                'description_en' => 'An advanced building set from sluban ModelBricks to construct the WZ-10S helicopter with a metal coating.',
                'description_ar' => 'مجموعة تركيب متقدمة من سلوبان موديل بريكس لبناء هليكوبتر WZ-10S.',
                'price' => 51.72,
                'stock' => 18,
                'thumbnail' => 'M38-B1233.webp',
                'images' => 'M38-B1233-3.webp, M38-B1233-2.webp, M38-B1233-1.webp',
            ],
            [
                'sku' => 'M38-B1220',
                'name_en' => 'sluban Metropolis Police – Central Police Station (Pull Back)',
                'name_ar' => 'سلوبان متروبوليس شرطة – مركز الشرطة المركزي (خاصية السحب للخلف)',
                'description_en' => 'A fantastic building set from sluban Metropolis Police to construct the Central Police Station.',
                'description_ar' => 'مجموعة تركيب رائعة من سلوبان متروبوليس شرطة لبناء مركز الشرطة المركزي.',
                'price' => 38.78,
                'stock' => 40,
                'thumbnail' => 'M38-B1220.webp',
                'images' => 'M38-B1220-4.webp, M38-B1220-3.webp, M38-B1220-2.webp, M38-B1220-1.webp',
            ],
            [
                'sku' => 'M38-B1129',
                'name_en' => 'sluban ModelBricks S1000MS Motorcycle 1/12 – 242 Pieces',
                'name_ar' => 'سلوبان موديل بريكس دراجة نارية S1000MS بمقياس 1/12 – 242 قطعة',
                'description_en' => 'A building set from sluban ModelBricks to construct the S1000MS motorcycle at 1/12 scale.',
                'description_ar' => 'مجموعة تركيب من سلوبان موديل بريكس لبناء دراجة نارية S1000MS.',
                'price' => 11.20,
                'stock' => 108,
                'thumbnail' => 'M38-B1129.webp',
                'images' => 'M38-B1129-4.webp, M38-B1129-3.webp, M38-B1129-2.webp, M38-B1129-1.webp',
            ],
            [
                'sku' => 'M38-B1218',
                'name_en' => 'sluban Metropolis Police – Escort Criminal Yuri (Pull Back)',
                'name_ar' => 'سلوبان متروبوليس شرطة – مرافقة المجرم يوري (خاصية السحب للخلف)',
                'description_en' => 'A fun building set from sluban Metropolis Police to create the Escort Criminal Yuri scene.',
                'description_ar' => 'مجموعة تركيب ممتعة من سلوبان متروبوليس شرطة لبناء مشهد مرافقة المجرم يوري.',
                'price' => 14.65,
                'stock' => 48,
                'thumbnail' => 'M38-B1218.webp',
                'images' => 'M38-B1218-4.webp, M38-B1218-3.webp, M38-B1218-2.webp, M38-B1218-1.webp',
            ],
            [
                'sku' => 'M38-B1216',
                'name_en' => 'sluban Metropolis Doctor – Dream City Hospital (Pull Back)',
                'name_ar' => 'سلوبان متروبوليس – مستشفى مدينة الأحلام (خاصية السحب للخلف)',
                'description_en' => 'A fun building set from sluban Metropolis to construct the Dream City Hospital.',
                'description_ar' => 'مجموعة تركيب ممتعة من سلوبان متروبوليس لبناء مستشفى مدينة الأحلام.',
                'price' => 38.78,
                'stock' => 40,
                'thumbnail' => 'M38-B1216.webp',
                'images' => 'M38-B1216-1.webp, M38-B1216-2.webp, M38-B1216-3.webp, M38-B1216-4.webp, M38-B1216-5.webp',
            ],
            [
                'sku' => 'M38-B1215',
                'name_en' => 'sluban Metropolis Doctor – Mobile Nursing Car (Pull Back)',
                'name_ar' => 'سلوبان متروبوليس – سيارة التمريض المتنقلة (خاصية السحب للخلف)',
                'description_en' => 'A fun building set from sluban Metropolis to construct the Mobile Nursing Car.',
                'description_ar' => 'مجموعة تركيب ممتعة من سلوبان متروبوليس لبناء سيارة التمريض المتنقلة.',
                'price' => 21.54,
                'stock' => 36,
                'thumbnail' => 'M38-B1215.webp',
                'images' => 'M38-B1215-6.webp, M38-B1215-5.webp, M38-B1215-4.webp, M38-B1215-3.webp, M38-B1215-2.webp, M38-B1215-1.webp',
            ],
            [
                'sku' => 'M38-B1192',
                'name_en' => 'ModelBricks- 1/35 TS-2 camping 265pcs',
                'name_ar' => 'موديل بريكس – مركبة التخييم TS-2 بمقياس 1/35 – 265 قطعة',
                'description_en' => 'A compact and detailed building model inspired by outdoor adventure and travel.',
                'description_ar' => 'هو نموذج تركيب مستوحى من أجواء التخييم والمغامرات الخارجية.',
                'price' => 12.92,
                'stock' => 48,
                'thumbnail' => 'M38-B1192.webp',
                'images' => 'M38-B1192-1.webp, M38-B1192-2.webp',
            ],
            [
                'sku' => 'M38-B1132',
                'name_en' => 'ModelBricks- R1250 MS Motorcycle 1/12 (200PCS)',
                'name_ar' => 'موديل بريكس – دراجة نارية R1250 MS بمقياس 1/12 – 200 قطعة',
                'description_en' => 'A detailed construction model inspired by modern touring motorcycles.',
                'description_ar' => 'هو نموذج تركيب دقيق مستوحى من الدراجات النارية الحديثة.',
                'price' => 11.20,
                'stock' => 108,
                'thumbnail' => 'M38-B1132.webp',
                'images' => 'M38-B1132-1.webp',
            ],
        ];

        foreach ($products as $productData) {
            // Check if product already exists
            if (Product::where('sku', $productData['sku'])->exists()) {
                continue;
            }

            $product = Product::create([
                'category_id' => $buildingModels->id,
                'name' => $productData['name_en'],
                'name_ar' => $productData['name_ar'],
                'slug' => Str::slug($productData['name_en']),
                'description' => $productData['description_en'],
                'description_ar' => $productData['description_ar'],
                'short_description' => Str::limit($productData['description_en'], 150),
                'short_description_ar' => Str::limit($productData['description_ar'], 150),
                'price' => $productData['price'],
                'compare_price' => null,
                'sku' => $productData['sku'],
                'stock' => $productData['stock'],
                'is_active' => true,
                'is_featured' => false,
                'times_purchased' => rand(10, 100),
                'average_rating' => rand(35, 50) / 10,
                'rating_count' => rand(5, 50),
                'view_count' => rand(100, 500),
            ]);

            // Create primary product image
            ProductImage::create([
                'product_id' => $product->id,
                'path' => "products/sluban/{$productData['thumbnail']}",
                'alt_text' => $product->name,
                'sort_order' => 0,
                'is_primary' => true,
            ]);

            // Create additional product images
            if (!empty($productData['images'])) {
                $additionalImages = array_filter(array_map('trim', explode(',', $productData['images'])));
                $sortOrder = 1;
                foreach ($additionalImages as $imageName) {
                    if (!empty($imageName)) {
                        ProductImage::create([
                            'product_id' => $product->id,
                            'path' => "products/sluban/{$imageName}",
                            'alt_text' => $product->name,
                            'sort_order' => $sortOrder++,
                            'is_primary' => false,
                        ]);
                    }
                }
            }
        }
    }
}
