<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Electronics - Smartphones (7 products)
            [
                'category' => 'smartphones',
                'name' => 'iPhone 15 Pro Max 256GB',
                'name_ar' => 'آيفون 15 برو ماكس 256 جيجابايت',
                'short' => 'Apple\'s flagship with A17 Pro chip, titanium design, and 48MP camera system.',
                'short_ar' => 'الرائد من أبل مع شريحة A17 Pro وتصميم تيتانيوم وكاميرا 48 ميجابكسل.',
                'price' => 1399.00,
                'compare' => null,
                'stock' => 25,
                'featured' => true,
                'times_purchased' => 156,
                'average_rating' => 4.8,
                'rating_count' => 89,
                'view_count' => 2340,
            ],
            [
                'category' => 'smartphones',
                'name' => 'Samsung Galaxy S24 Ultra',
                'name_ar' => 'سامسونج جالكسي S24 الترا',
                'short' => 'AI-powered Galaxy with S Pen, 200MP camera, and Snapdragon 8 Gen 3.',
                'short_ar' => 'جالكسي مدعوم بالذكاء الاصطناعي مع قلم S وكاميرا 200 ميجابكسل ومعالج سناب دراجون 8 الجيل الثالث.',
                'price' => 1299.00,
                'compare' => 1449.00,
                'stock' => 18,
                'featured' => true,
                'times_purchased' => 203,
                'average_rating' => 4.7,
                'rating_count' => 124,
                'view_count' => 3150,
            ],
            [
                'category' => 'smartphones',
                'name' => 'Xiaomi 14 Pro',
                'name_ar' => 'شاومي 14 برو',
                'short' => 'Leica optics, Snapdragon 8 Gen 3, and 120W HyperCharge.',
                'short_ar' => 'بصريات لايكا ومعالج سناب دراجون 8 الجيل الثالث وشحن سريع 120 واط.',
                'price' => 799.00,
                'compare' => 899.00,
                'stock' => 35,
                'featured' => false,
                'times_purchased' => 87,
                'average_rating' => 3.5,
                'rating_count' => 56,
                'view_count' => 1890,
            ],
            [
                'category' => 'smartphones',
                'name' => 'HUAWEI Mate 60 Pro',
                'name_ar' => 'هواوي ميت 60 برو',
                'short' => 'Satellite calling, Kirin 9000S chip, and variable aperture camera.',
                'short_ar' => 'اتصال بالأقمار الصناعية ومعالج كيرين 9000S وكاميرا بفتحة عدسة متغيرة.',
                'price' => 999.00,
                'compare' => null,
                'stock' => 12,
                'featured' => false,
                'times_purchased' => 34,
                'average_rating' => 3.0,
                'rating_count' => 23,
                'view_count' => 980,
            ],
            [
                'category' => 'smartphones',
                'name' => 'OPPO Reno 11 Pro',
                'name_ar' => 'أوبو رينو 11 برو',
                'short' => 'Portrait expert with Hasselblad color science and 80W fast charging.',
                'short_ar' => 'خبير البورتريه مع تقنية ألوان هاسيلبلاد وشحن سريع 80 واط.',
                'price' => 549.00,
                'compare' => 649.00,
                'stock' => 42,
                'featured' => false,
                'times_purchased' => 112,
                'average_rating' => 4.5,
                'rating_count' => 67,
                'view_count' => 1560,
            ],
            [
                'category' => 'smartphones',
                'name' => 'Google Pixel 8 Pro',
                'name_ar' => 'جوجل بكسل 8 برو',
                'short' => 'Best-in-class AI photography with Tensor G3 chip and 7 years of updates.',
                'short_ar' => 'أفضل تصوير بالذكاء الاصطناعي مع معالج تينسور G3 و7 سنوات من التحديثات.',
                'price' => 999.00,
                'compare' => 1099.00,
                'stock' => 20,
                'featured' => true,
                'times_purchased' => 145,
                'average_rating' => 4.6,
                'rating_count' => 98,
                'view_count' => 2780,
            ],
            [
                'category' => 'smartphones',
                'name' => 'OnePlus 12',
                'name_ar' => 'ون بلس 12',
                'short' => 'Flagship killer with Snapdragon 8 Gen 3 and 100W SUPERVOOC charging.',
                'short_ar' => 'قاتل الهواتف الرائدة مع سناب دراجون 8 الجيل الثالث وشحن سوبر فوك 100 واط.',
                'price' => 799.00,
                'compare' => null,
                'stock' => 28,
                'featured' => false,
                'times_purchased' => 78,
                'average_rating' => 4.5,
                'rating_count' => 45,
                'view_count' => 1340,
            ],

            // Electronics - Laptops (7 products)
            [
                'category' => 'laptops',
                'name' => 'MacBook Pro 14" M3 Pro',
                'name_ar' => 'ماك بوك برو 14 بوصة M3 برو',
                'short' => 'Apple silicon powerhouse with Liquid Retina XDR display and 18-hour battery.',
                'short_ar' => 'قوة معالج أبل سيليكون مع شاشة ليكويد ريتينا XDR وبطارية 18 ساعة.',
                'price' => 1999.00,
                'compare' => null,
                'stock' => 8,
                'featured' => true,
                'low_threshold' => 5,
                'times_purchased' => 89,
                'average_rating' => 4.9,
                'rating_count' => 67,
                'view_count' => 2890,
            ],
            [
                'category' => 'laptops',
                'name' => 'Dell XPS 15 (2024)',
                'name_ar' => 'ديل XPS 15 (2024)',
                'short' => 'Intel Core Ultra, OLED display, and premium aluminum build.',
                'short_ar' => 'معالج إنتل كور ألترا وشاشة OLED وهيكل ألمنيوم فاخر.',
                'price' => 1599.00,
                'compare' => 1799.00,
                'stock' => 15,
                'featured' => true,
                'times_purchased' => 67,
                'average_rating' => 4.6,
                'rating_count' => 43,
                'view_count' => 1980,
            ],
            [
                'category' => 'laptops',
                'name' => 'ASUS ROG Strix G16',
                'name_ar' => 'أسوس روج ستريكس G16',
                'short' => 'RTX 4070 gaming laptop with 165Hz display and RGB lighting.',
                'short_ar' => 'لابتوب ألعاب RTX 4070 مع شاشة 165Hz وإضاءة RGB.',
                'price' => 1449.00,
                'compare' => null,
                'stock' => 10,
                'featured' => false,
                'times_purchased' => 45,
                'average_rating' => 4.7,
                'rating_count' => 34,
                'view_count' => 2340,
            ],
            [
                'category' => 'laptops',
                'name' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'name_ar' => 'لينوفو ثينك باد X1 كاربون الجيل 11',
                'short' => 'Business ultrabook with Intel vPro, 4G LTE, and legendary keyboard.',
                'short_ar' => 'ألترابوك للأعمال مع إنتل vPro و4G LTE ولوحة مفاتيح أسطورية.',
                'price' => 1699.00,
                'compare' => 1899.00,
                'stock' => 6,
                'featured' => false,
                'low_threshold' => 5,
                'times_purchased' => 38,
                'average_rating' => 4.8,
                'rating_count' => 29,
                'view_count' => 1120,
            ],
            [
                'category' => 'laptops',
                'name' => 'HP Pavilion 15',
                'name_ar' => 'إتش بي بافيليون 15',
                'short' => 'Affordable everyday laptop with Intel Core i5 and 512GB SSD.',
                'short_ar' => 'لابتوب يومي بسعر مناسب مع معالج إنتل كور i5 و512 جيجابايت SSD.',
                'price' => 549.00,
                'compare' => 649.00,
                'stock' => 45,
                'featured' => false,
                'times_purchased' => 234,
                'average_rating' => 3.5,
                'rating_count' => 156,
                'view_count' => 4560,
            ],
            [
                'category' => 'laptops',
                'name' => 'Microsoft Surface Laptop 5',
                'name_ar' => 'مايكروسوفت سيرفس لابتوب 5',
                'short' => 'Sleek design with PixelSense touchscreen and all-day battery life.',
                'short_ar' => 'تصميم أنيق مع شاشة لمس بكسل سينس وبطارية تدوم طوال اليوم.',
                'price' => 1299.00,
                'compare' => null,
                'stock' => 12,
                'featured' => false,
                'times_purchased' => 52,
                'average_rating' => 4.4,
                'rating_count' => 38,
                'view_count' => 1670,
            ],
            [
                'category' => 'laptops',
                'name' => 'Acer Swift Go 14',
                'name_ar' => 'أيسر سويفت جو 14',
                'short' => 'Ultra-portable with Intel Core Ultra and stunning 2.8K OLED display.',
                'short_ar' => 'خفيف جداً مع معالج إنتل كور ألترا وشاشة OLED مذهلة بدقة 2.8K.',
                'price' => 899.00,
                'compare' => 999.00,
                'stock' => 22,
                'featured' => false,
                'times_purchased' => 76,
                'average_rating' => 4.3,
                'rating_count' => 51,
                'view_count' => 1890,
            ],

            // Electronics - Accessories (6 products)
            [
                'category' => 'accessories',
                'name' => 'Apple AirPods Pro 2nd Gen',
                'name_ar' => 'أبل إيربودز برو الجيل الثاني',
                'short' => 'Active noise cancellation, spatial audio, and USB-C charging case.',
                'short_ar' => 'إلغاء الضوضاء النشط والصوت المكاني وعلبة شحن USB-C.',
                'price' => 249.00,
                'compare' => null,
                'stock' => 65,
                'featured' => true,
                'times_purchased' => 312,
                'average_rating' => 4.8,
                'rating_count' => 234,
                'view_count' => 5670,
            ],
            [
                'category' => 'accessories',
                'name' => 'Samsung 25W USB-C Charger',
                'name_ar' => 'شاحن سامسونج 25 واط USB-C',
                'short' => 'Super fast charging adapter compatible with Galaxy devices.',
                'short_ar' => 'محول شحن سريع جداً متوافق مع أجهزة جالكسي.',
                'price' => 29.00,
                'compare' => 39.00,
                'stock' => 150,
                'featured' => false,
                'times_purchased' => 567,
                'average_rating' => 4.5,
                'rating_count' => 312,
                'view_count' => 3450,
            ],
            [
                'category' => 'accessories',
                'name' => 'Anker PowerCore 20000mAh',
                'name_ar' => 'أنكر باور كور 20000 مللي أمبير',
                'short' => 'High-capacity power bank with dual USB ports and fast charging.',
                'short_ar' => 'بطارية خارجية عالية السعة مع منفذين USB وشحن سريع.',
                'price' => 59.00,
                'compare' => null,
                'stock' => 85,
                'featured' => false,
                'times_purchased' => 289,
                'average_rating' => 4.6,
                'rating_count' => 198,
                'view_count' => 2890,
            ],
            [
                'category' => 'accessories',
                'name' => 'Logitech MX Master 3S',
                'name_ar' => 'لوجيتك MX ماستر 3S',
                'short' => 'Quiet clicks, 8K DPI sensor, and MagSpeed electromagnetic scrolling.',
                'short_ar' => 'نقرات هادئة ومستشعر 8K DPI وتمرير كهرومغناطيسي MagSpeed.',
                'price' => 99.00,
                'compare' => 119.00,
                'stock' => 40,
                'featured' => true,
                'times_purchased' => 178,
                'average_rating' => 4.9,
                'rating_count' => 145,
                'view_count' => 3120,
            ],
            [
                'category' => 'accessories',
                'name' => 'JBL Tune 760NC Headphones',
                'name_ar' => 'سماعات JBL تيون 760NC',
                'short' => 'Wireless over-ear headphones with active noise cancelling and 50hr battery.',
                'short_ar' => 'سماعات لاسلكية فوق الأذن مع إلغاء الضوضاء النشط وبطارية 50 ساعة.',
                'price' => 119.00,
                'compare' => 149.00,
                'stock' => 55,
                'featured' => false,
                'times_purchased' => 156,
                'average_rating' => 4.4,
                'rating_count' => 112,
                'view_count' => 2340,
            ],
            [
                'category' => 'accessories',
                'name' => 'Apple Watch Series 9',
                'name_ar' => 'أبل واتش سيريز 9',
                'short' => 'Advanced health features with double tap gesture and brighter display.',
                'short_ar' => 'ميزات صحية متقدمة مع إيماءة النقر المزدوج وشاشة أكثر سطوعاً.',
                'price' => 429.00,
                'compare' => null,
                'stock' => 30,
                'featured' => true,
                'times_purchased' => 134,
                'average_rating' => 4.7,
                'rating_count' => 89,
                'view_count' => 3890,
            ],

            // Skincare (5 products)
            [
                'category' => 'skincare',
                'name' => 'La Roche-Posay Effaclar Duo',
                'name_ar' => 'لاروش بوزيه إيفاكلار ديو',
                'short' => 'Dual action acne treatment for oily and blemish-prone skin.',
                'short_ar' => 'علاج مزدوج الفعالية لحب الشباب للبشرة الدهنية والمعرضة للشوائب.',
                'price' => 28.00,
                'compare' => null,
                'stock' => 75,
                'featured' => false,
                'times_purchased' => 198,
                'average_rating' => 4.5,
                'rating_count' => 134,
                'view_count' => 2780,
            ],
            [
                'category' => 'skincare',
                'name' => 'CeraVe Moisturizing Cream',
                'name_ar' => 'كريم سيرافي المرطب',
                'short' => 'Rich cream with ceramides and hyaluronic acid for 24hr hydration.',
                'short_ar' => 'كريم غني بالسيراميد وحمض الهيالورونيك لترطيب 24 ساعة.',
                'price' => 19.00,
                'compare' => 25.00,
                'stock' => 110,
                'featured' => true,
                'times_purchased' => 456,
                'average_rating' => 4.8,
                'rating_count' => 298,
                'view_count' => 6780,
            ],
            [
                'category' => 'skincare',
                'name' => 'The Ordinary Niacinamide 10%',
                'name_ar' => 'ذا أورديناري نياسيناميد 10%',
                'short' => 'Serum for reducing blemishes and balancing sebum.',
                'short_ar' => 'سيروم لتقليل الشوائب وموازنة الدهون.',
                'price' => 12.00,
                'compare' => null,
                'stock' => 95,
                'featured' => false,
                'times_purchased' => 534,
                'average_rating' => 4.6,
                'rating_count' => 367,
                'view_count' => 5430,
            ],
            [
                'category' => 'skincare',
                'name' => 'Dead Sea Mud Mask',
                'name_ar' => 'قناع طين البحر الميت',
                'short' => 'Authentic Jordan Dead Sea mud for deep pore cleansing.',
                'short_ar' => 'طين البحر الميت الأردني الأصلي لتنظيف المسام بعمق.',
                'price' => 24.00,
                'compare' => 32.00,
                'stock' => 60,
                'featured' => true,
                'times_purchased' => 267,
                'average_rating' => 4.7,
                'rating_count' => 189,
                'view_count' => 3450,
            ],
            [
                'category' => 'skincare',
                'name' => 'Bioderma Sensibio H2O Micellar',
                'name_ar' => 'بيوديرما سينسيبيو H2O ميسيلار',
                'short' => 'Gentle makeup remover for sensitive skin, 500ml.',
                'short_ar' => 'مزيل مكياج لطيف للبشرة الحساسة، 500 مل.',
                'price' => 22.00,
                'compare' => null,
                'stock' => 85,
                'featured' => false,
                'times_purchased' => 312,
                'average_rating' => 4.6,
                'rating_count' => 234,
                'view_count' => 2980,
            ],
        ];

        foreach ($products as $productData) {
            $category = Category::where('slug', $productData['category'])->first();

            if (!$category) {
                continue;
            }

            $product = Product::create([
                'category_id' => $category->id,
                'name' => $productData['name'],
                'name_ar' => $productData['name_ar'],
                'slug' => Str::slug($productData['name']),
                'description' => $this->generateDescription($productData['name'], $productData['short']),
                'description_ar' => $productData['short_ar'],
                'short_description' => $productData['short'],
                'short_description_ar' => $productData['short_ar'],
                'price' => $productData['price'],
                'compare_price' => $productData['compare'],
                'sku' => $this->generateSku($category->slug),
                'stock' => $productData['stock'],
                'low_stock_threshold' => $productData['low_threshold'] ?? null,
                'is_active' => true,
                'is_featured' => $productData['featured'],
                'times_purchased' => $productData['times_purchased'] ?? 0,
                'average_rating' => $productData['average_rating'] ?? 0,
                'rating_count' => $productData['rating_count'] ?? 0,
                'view_count' => $productData['view_count'] ?? 0,
            ]);

            // Create product image using product slug
            ProductImage::create([
                'product_id' => $product->id,
                'path' => "products/{$product->slug}.webp",
                'alt_text' => $product->name,
                'sort_order' => 0,
                'is_primary' => true,
            ]);
        }
    }

    private function generateSku(string $categorySlug): string
    {
        $prefix = match ($categorySlug) {
            'smartphones' => 'PHN',
            'laptops' => 'LAP',
            'accessories' => 'ACC',
            'skincare' => 'SKN',
            default => 'PRD',
        };

        return $prefix . '-' . strtoupper(Str::random(2)) . rand(1000, 9999);
    }

    private function generateDescription(string $name, string $shortDesc): string
    {
        return "{$shortDesc}";
    }
}
